org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Parchment (community mappings)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.10

# Core versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.228
neo_version_range=[21.1,)
loader_version_range=[1,)

# JEI
jei_version=19.27.0.340

# Mekanism
mekanism_version=10.7.19.85

# Mod metadata
mod_id=energyblade
mod_name=HF Blade
mod_license=MIT License
mod_version=1.0.3-1.21.1
mod_group_id=cn.mmf.energyblade
mod_authors=Arcomit, Syameimaru Zheng

maven_loc=/D:/maven/MMMaven/repository
